# docker-compose.yml
version: '3.8'

services:
  group1_web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - group1_db
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=group1_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=group1_shareride_db

  group1_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: group1_shareride_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  group1_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: group1_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - group1_db

volumes:
  db_data: